FROM python:3.8-alpine

LABEL maintainer="test@test.com"
ARG test=1.0.0


WORKDIR /app
ADD . /app


# RUN apt-get install debian-keyring debain-archive-keyring
# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 54404762BBB6E853 0E98404D386FA1D9 F8D2585B8783D481 54404762BBB6E853 BDE6D2B9216EC7A8

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     wget \
#     curl && \
#     rm -rf /var/lib/apt/lists/*

# RUN /usr/local/bin/python -m pip install --no-cache --upgrade pip

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

EXPOSE 5000

CMD ["python", "run.py"]
