FROM python:3.8-alpine

LABEL maintainer="test@mysqlt.com"
ARG test=1.0.0

WORKDIR /app
ADD . /app

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

EXPOSE 5000

CMD ["python", "run.py"]